

CREATE DATABASE IF NOT EXISTS `id4956438_tienda` DEFAULT CHARACTER SET utf32 COLLATE utf32_spanish_ci;

USE `id4956438_tienda`;


CREATE TABLE `CLIENTE` (
  `IDCLIENTE` int(11) NOT NULL,
  `IDUSUARIO` int(11) DEFAULT NULL,
  `NOMBRE` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `APELLIDO` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `TELEFONO` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `DIRECCION` varchar(100) COLLATE utf32_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `COMPRAS` (
  `IDCOMPRA` int(11) NOT NULL,
  `IDPEDIDO` varchar(32) COLLATE utf32_spanish_ci DEFAULT NULL,
  `MONTO` double DEFAULT NULL,
  `RAZONSOCIAL` varchar(100) COLLATE utf32_spanish_ci DEFAULT NULL,
  `RIFCI` varchar(40) COLLATE utf32_spanish_ci DEFAULT NULL,
  `DIRFISCAL` varchar(200) COLLATE utf32_spanish_ci DEFAULT NULL,
  `FECHAPAGO` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `ENVIOS` (
  `IDENVIO` int(11) NOT NULL,
  `IDPEDIDO` varchar(32) COLLATE utf32_spanish_ci DEFAULT NULL,
  `PAIS` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `ESTADO` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `CIUDAD` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `MUNICIPIO` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `PARROQUIA` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `DIRECCION` varchar(200) COLLATE utf32_spanish_ci DEFAULT NULL,
  `CODIGOPOSTAL` varchar(20) COLLATE utf32_spanish_ci DEFAULT NULL,
  `RECEPTOR` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `CIRECEPTOR` varchar(40) COLLATE utf32_spanish_ci DEFAULT NULL,
  `TELFRECEPTOR` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `OBSERVACIONES` varchar(100) COLLATE utf32_spanish_ci DEFAULT NULL,
  `GUIA` varchar(50) COLLATE utf32_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `FALLA` (
  `IDFALLA` int(11) NOT NULL,
  `IDPEDIDO` varchar(32) COLLATE utf32_spanish_ci DEFAULT NULL,
  `COMENTARIO` varchar(200) COLLATE utf32_spanish_ci DEFAULT NULL,
  `FECHAFALLA` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `INVENTARIO` (
  `IDINVENTARIO` int(11) NOT NULL,
  `IDPRODUCTO` int(11) DEFAULT NULL,
  `TALLA` varchar(4) COLLATE utf32_spanish_ci DEFAULT NULL,
  `CANTIDAD` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `ITEMS` (
  `IDPEDIDO` varchar(32) COLLATE utf32_spanish_ci DEFAULT NULL,
  `IDINVENTARIO` int(11) DEFAULT NULL,
  `CANTIDAD` int(10) UNSIGNED DEFAULT NULL,
  `PRECIO` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `PEDIDOS` (
 `IDPEDIDO` varchar(32) COLLATE utf32_spanish_ci NOT NULL,
  `CLIENTE` varchar(50) COLLATE utf32_spanish_ci DEFAULT NULL,
  `TELEFONO` varchar(20) COLLATE utf32_spanish_ci DEFAULT NULL,
  `EMAIL` varchar(50) COLLATE utf32_spanish_ci DEFAULT NULL,
  `ESTATUS` int(11) DEFAULT NULL,
  `FECHAPEDIDO` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `PRODUCTO` (
  `IDPRODUCTO` int(11) NOT NULL,
  `NOMBRE_P` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `DESCRIPCION` varchar(250) COLLATE utf32_spanish_ci DEFAULT NULL,
  `GENERO` int(11)NOT NULL,
  `TIPO` varchar(30) COLLATE utf32_spanish_ci NOT NULL,
  `PRECIO` float DEFAULT NULL,
  `IMAGEN` varchar(50) COLLATE utf32_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `USUARIO` (
  `IDUSUARIO` int(11) NOT NULL,
  `CORREO` varchar(30) COLLATE utf32_spanish_ci DEFAULT NULL,
  `CLAVE` varchar(50) COLLATE utf32_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;


CREATE TABLE `VARIABLES` (
  `IDVARIABLE` int(11) NOT NULL,
  `NOMBRE` varchar(10) COLLATE utf32_spanish_ci DEFAULT NULL,
  `VALUE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci;



ALTER TABLE `CLIENTE`
  ADD PRIMARY KEY (`IDCLIENTE`),
  ADD UNIQUE KEY `IDUSUARIO` (`IDUSUARIO`);


ALTER TABLE `COMPRAS`
  ADD PRIMARY KEY (`IDCOMPRA`),
  ADD KEY `IDPEDIDO` (`IDPEDIDO`);

ALTER TABLE `ENVIOS`
  ADD PRIMARY KEY (`IDENVIO`),
  ADD KEY `IDPEDIDO` (`IDPEDIDO`);

ALTER TABLE `FALLA`
  ADD PRIMARY KEY (`IDFALLA`);


ALTER TABLE `INVENTARIO`
  ADD PRIMARY KEY (`IDINVENTARIO`),
  ADD UNIQUE KEY `IDINVENTARIO` (`IDINVENTARIO`),
  ADD KEY `IDPRODUCTO` (`IDPRODUCTO`);


ALTER TABLE `ITEMS`
  ADD KEY `IDPEDIDO` (`IDPEDIDO`);


ALTER TABLE `PEDIDOS`
  ADD PRIMARY KEY (`IDPEDIDO`);


ALTER TABLE `PRODUCTO`
  ADD PRIMARY KEY (`IDPRODUCTO`),
  ADD UNIQUE KEY `IDPRODUCTO` (`IDPRODUCTO`);


ALTER TABLE `USUARIO`
  ADD PRIMARY KEY (`IDUSUARIO`),
  ADD UNIQUE KEY `CORREO` (`CORREO`);


ALTER TABLE `VARIABLES`
  ADD PRIMARY KEY (`IDVARIABLE`);



ALTER TABLE `CLIENTE`
  MODIFY `IDCLIENTE` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `COMPRAS`
  MODIFY `IDCOMPRA` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;


ALTER TABLE `ENVIOS`
  MODIFY `IDENVIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=68;


ALTER TABLE `FALLA`
  MODIFY `IDFALLA` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `INVENTARIO`
  MODIFY `IDINVENTARIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;


ALTER TABLE `PRODUCTO`
  MODIFY `IDPRODUCTO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;


ALTER TABLE `USUARIO`
  MODIFY `IDUSUARIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;


ALTER TABLE `VARIABLES`
  MODIFY `IDVARIABLE` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;



ALTER TABLE `COMPRAS`
  ADD CONSTRAINT `COMPRAS_ibfk_1` FOREIGN KEY (`IDPEDIDO`) REFERENCES `PEDIDOS` (`IDPEDIDO`) ON DELETE CASCADE;


ALTER TABLE `ENVIOS`
  ADD CONSTRAINT `ENVIOS_ibfk_1` FOREIGN KEY (`IDPEDIDO`) REFERENCES `PEDIDOS` (`IDPEDIDO`) ON DELETE CASCADE;


ALTER TABLE `INVENTARIO`
  ADD CONSTRAINT `INVENTARIO_ibfk_1` FOREIGN KEY (`IDPRODUCTO`) REFERENCES `PRODUCTO` (`IDPRODUCTO`) ON DELETE CASCADE;


ALTER TABLE `ITEMS`
  ADD CONSTRAINT `ITEMS_ibfk_1` FOREIGN KEY (`IDPEDIDO`) REFERENCES `PEDIDOS` (`IDPEDIDO`) ON DELETE CASCADE;